language: node_js
node_js:
  - 10.7.0

jobs:
  include:
    - stage: tests
      name: "Linter"
      script: npm run lint

    - stage: tests
      name: "Unit tests"
      script: 
        - cd test && npm install 
        - cd .. && npm run test && npm run coverage
    

